### ISSUE TITLE
不觉得关注公众号才能看，很恶心么？

### ISSUE THREAD

**Issue by wenbochang888** [fuzhengwei/itstack-demo-design#12]
扫码或搜索：bugstack虫洞栈
发送 1D3B8E
即可立即永久解锁本站全部文章

真的恶心，点了赞之后，我又给取消了

**Comment by fuzhengwei** [comment]
> 扫码或搜索：bugstack虫洞栈
> 发送 1D3B8E
> 即可立即永久解锁本站全部文章
> 
> 真的恶心，点了赞之后，我又给取消了

嗯，让人怪不好意思的😄，咋说呢，如下吧：
1. 我和你一样，都是走在这条路上的程序员
2. 但从某一天开始我做公众号了，为了可以有更多的粉丝关注，我确实需要做一些营销策略
3. 这些博客、公众号、GitHub、文章等，都需要投入大量的时间、经历和一部分资金
4. 而我也没有接广告、或者其他割韭菜内容，所以我是一个人在投入个人经历，建设一个技术社区
5. 最终，让大家关注公众号，也是为了可以阅读到我更多的文章，知道我的技术内容推送
6. 好了，希望理解，也可以添加我的微信：fustack

**Comment by daleyzou** [comment]
支持作者，只用爱发电是不能长久的

**Comment by furundong** [comment]
> 扫码或搜索：bugstack虫洞栈
> 发送 1D3B8E
> 即可立即永久解锁本站全部文章
> 
> 真的恶心，点了赞之后，我又给取消了



> 扫码或搜索：bugstack虫洞栈
> 发送 1D3B8E
> 即可立即永久解锁本站全部文章
> 
> 真的恶心，点了赞之后，我又给取消了

hahaha，我也是star后又取消了，但是我看了你的评论我又重新点了起来

**Comment by fuzhengwei** [comment]
> > 扫码或搜索：bugstack虫洞栈
> > 发送 1D3B8E
> > 即可立即永久解锁本站全部文章
> > 真的恶心，点了赞之后，我又给取消了
> 
> > 扫码或搜索：bugstack虫洞栈
> > 发送 1D3B8E
> > 即可立即永久解锁本站全部文章
> > 真的恶心，点了赞之后，我又给取消了
> 
> hahaha，我也是star后又取消了，但是我看了你的评论我又重新点了起来

哈哈哈，加个微信吧，fustack

**Comment by AlbertZyc** [comment]
用爱给你发电？

**Comment by iheyunfei** [comment]
绝了，白嫖有理了？不想看不看，别人写了文章这个价钱，觉得不值不看就是了

**Comment by githubhxd1995** [comment]
🤣

**Comment by tomdegithub** [comment]
真乃神人也, 白嫖也能如此理直气壮啊!

**Comment by wenbochang888** [comment]
写技术文章并不是为了赚钱，而是为了提升自己。如果要赚钱，请备注开源协议
