### ISSUE TITLE
你好，想问个代码中的问题

### ISSUE THREAD

**Issue by meshow1** [fuzhengwei/itstack-demo-design#15]
作者你好，在看书中有个代码的实现细节不是很懂。
1.
在设计模式部分的itstack-demo-design项目中的itstack-demo-design/itstack-demo-design-2-02/src/main/java/org/itstack/demo/desgin/factory/JDKProxy.java 这个类里的方法
 getProxy(Class《T》 interfaceClass, ICacheAdapter cacheAdapter)
中第一个参数是带泛型T，然后最后返回的值进行类型转换
return (T) Proxy.newProxyInstance(classLoader, new Class[]{classes[0]}, handler);
[我想问的是在测试的时候](https://github.com/fuzhengwei/itstack-demo-design/blob/master/itstack-demo-design-2-02/src/test/java/org/itstack/demo/desgin/test/ApiTest.java)
CacheService proxy_EGM = JDKProxy.getProxy(CacheServiceImpl.class, new EGMCacheAdapter());
这句话为什么第一个参数传入的是实现类的类对象，而不是接口的类型？
因为我看的一些动态代理介绍说的是对于产生的代理对象，不能强转为实现类，只能转为接口类型。
可能我对泛型理解的有问题 : (
2.第二个问题是对于设计模式这本书中，在其他资料上介绍说抽象工厂是工厂的工厂，我想问一下本书中的通过代理实现的抽象工厂，返回的这个代理对象是不是就是其他资料上指的，由抽象工厂产生的工厂？因为刚学设计模式，书里也没有明确点出，看的不是很懂。

**Comment by fuzhengwei** [comment]
> 作者你好，在看书中有个代码的实现细节不是很懂。
> 1.
> 在设计模式部分的itstack-demo-design项目中的itstack-demo-design/itstack-demo-design-2-02/src/main/java/org/itstack/demo/desgin/factory/JDKProxy.java 这个类里的方法
> getProxy(Class《T》 interfaceClass, ICacheAdapter cacheAdapter)
> 中第一个参数是带泛型T，然后最后返回的值进行类型转换
> return (T) Proxy.newProxyInstance(classLoader, new Class[]{classes[0]}, handler);
> [我想问的是在测试的时候](https://github.com/fuzhengwei/itstack-demo-design/blob/master/itstack-demo-design-2-02/src/test/java/org/itstack/demo/desgin/test/ApiTest.java)
> CacheService proxy_EGM = JDKProxy.getProxy(CacheServiceImpl.class, new EGMCacheAdapter());
> 这句话为什么第一个参数传入的是实现类的类对象，而不是接口的类型？
> 因为我看的一些动态代理介绍说的是对于产生的代理对象，不能强转为实现类，只能转为接口类型。
> 可能我对泛型理解的有问题 : (
> 2.第二个问题是对于设计模式这本书中，在其他资料上介绍说抽象工厂是工厂的工厂，我想问一下本书中的通过代理实现的抽象工厂，返回的这个代理对象是不是就是其他资料上指的，由抽象工厂产生的工厂？因为刚学设计模式，书里也没有明确点出，看的不是很懂。

1. `而不是接口的类型`，可以是接口类型，但是代码里需要修改下。*代码里自己获取了接口类型*
2. 嗯，返回的就是工厂的工厂，用于使用不同的缓存服务

**Comment by meshow1** [comment]
了解，感谢回复：）
