### ISSUE TITLE
编译打包项目，一大堆报错

### ISSUE THREAD

**Issue by ZhengWenQi98** [fuzhengwei/itstack-demo-design#19]
第一个报错是某个工程使用了其他工程的类，但是没引入依赖，
第二个报错是，maven使用了Java1.6版本的插件编译项目，导致语法不支持报错
第三个报错则是下面这个，还有一些其他报错就不列举了
[ERROR] Failed to execute goal on project itstack-demo-design-10-01: Could not resolve dependencies for project org.itstack:itstack-demo-design-10-01:jar:1.0-SNAPSHOT: Could not find artifact org.springframework.boot:itstack-demo-design-10-00:jar:2.1.2.RELEASE in alimaven (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :itstack-demo-design-10-01

**Comment by fuzhengwei** [comment]
每一组是一个

> 第一个报错是某个工程使用了其他工程的类，但是没引入依赖，
> 第二个报错是，maven使用了Java1.6版本的插件编译项目，导致语法不支持报错
> 第三个报错则是下面这个，还有一些其他报错就不列举了
> [ERROR] Failed to execute goal on project itstack-demo-design-10-01: Could not resolve dependencies for project org.itstack:itstack-demo-design-10-01:jar:1.0-SNAPSHOT: Could not find artifact org.springframework.boot:itstack-demo-design-10-00:jar:2.1.2.RELEASE in alimaven (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :itstack-demo-design-10-01

每一组是一个工程服务，比如1-00、1-01、1-02，打包时不要整体打包。
jdk可以设置下jdk1.8
