### ISSUE TITLE
门面模式-itstack-demo-design-10-02-字符串分割的问题

### ISSUE THREAD

**Issue by Gobaio** [fuzhengwei/itstack-demo-design#28]
itstack-demo-design-10-02
org.itstack.demo.design.door.config.StarterService#split(String separatorChar )
第20行,使用spring中的工具类,只能将一个字符串分割成两段.
return StringUtils.split(this.userStr, separatorChar);
如配置文件中 userStr: 1001,aaaa,ccc
使用这个方法会将字符串分割成 1001 和 aaaa,ccc两部分,并不会分割成1001、aaaa和ccc三部分
达不到配置多个白名单的效果

**Comment by fuzhengwei** [comment]
把 StringUtils 换一下，这个包的方法有问题
