### ISSUE TITLE
面向对象的设计模式如何与关系型数据库结合

### ISSUE THREAD

**Issue by lujinyongwh** [fuzhengwei/itstack-demo-design#34]
大佬，请问下，面向对象的设计模式如何与关系型数据库结合？
因为系统数据都是要存储的，99%都是要落关系型数据库，设计模式学完后还是没想到怎么和关系型数据库结合，设计系统的时候还是按照关系型数据表的存储来设计的。
请问下用设计模式，能提高此类系统的开发效率、开发质量、扩展性、可读性、复用性么？

**Comment by fuzhengwei** [comment]
1. 在系统设计上，需要考虑：数据结构、算法逻辑、设计模式、系统架构、服务部署、应用运维
2. 数据结构的设计主要包括了对数据库表的设计，在数据结构的基础上应用合理的设计模式，把数据用与之合适的代码逻辑编写算法实现，其实这些算法并不一定非得局限于排序、二分、贪心等，也包括了代码中的逻辑实现
3. 如果可以非常合理的运用设计模式开发相应的业务需求，那么在后续的扩展、易读和复用等，都会非常不错
