### ISSUE TITLE
责任链模式，代码run的结果有问题

### ISSUE THREAD

**Issue by Zhuoyuan1** [fuzhengwei/itstack-demo-design#52]
![1631934718(1)](https://user-images.githubusercontent.com/41421622/133870620-8177f7be-0620-4ab5-ac7d-cb37ea91700c.jpg)

**Comment by Zhuoyuan1** [comment]
![微信截图_20210918111549](https://user-images.githubusercontent.com/41421622/133870718-5bd65240-8f6a-402e-940c-22a85f6d344b.png)
也许需要这么改？

**Comment by Zhuoyuan1** [comment]
时间问题

**Comment by xlndql** [comment]
public AuthLink appendNext(AuthLink next) {
this.next = next;
return this;
}
这个是不是应该return next

**Comment by Tassel-s** [comment]
> 时间问题

更改AuthLink子类中的时间参数可以解决问题
